### ISSUE TITLE
Separate the cross-repo code from the actual runs

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/manageiq-cross_repo#22]
I'm thinking we create a `ManageIQ/manageiq-cross_repo` gem.  Then separately we have a `ManageIQ/manageiq-cross_repo-tests` repo, which has just a .travis.yml file and a Gemfile, and is where the requests are executed.  This way we can have tests on the cross_repo framework itself.

Not sure on the names, but that's the general idea.  @agrare Thoughts?

**Comment by agrare** [comment]
Ha I started working on specs for this gem and was going to ask you what you wanted to call the "test" repo.  `ManageIQ/manageiq-cross_repo-tests` sounds good to me

**Comment by agrare** [comment]
Some initial specs https://github.com/Fryguy/manageiq-cross_repo/pull/23
